<?php
/* Reset your password form, sends reset.php password link */
require 'db.php';
require 'PHPMailer/PHPMailerAutoload.php';

// Escape all $_POST variables to protect against SQL injections
$id = $mysqli->escape_string($_POST['id']);
$name = $mysqli->escape_string($_POST['name']);
$description = $mysqli->escape_string($_POST['description']);

$result = $mysqli->query("SELECT * FROM users WHERE id='$id'");

// Check if form submitted with method="post"
if ($result->num_rows == 0) // User doesn't exist
{
    $_SESSION['message'] = "User with that email doesn't exist!";
    header("location: error.php");
} else { // User exists (num_rows != 0)

    $user = $result->fetch_assoc();
    $email = $user['email'];

    // Send registration confirmation link (reset.php)
    //$mail = new PHPMailer();
    // SMTP Settings
    // $mail->isSMTP();                                      // Set mailer to use SMTP
    // $mail->Host = 'smtp.hostinger.com';                   // Specify main and backup SMTP servers
    // $mail->SMTPAuth = true;                               // Enable SMTP authentication
    // $mail->Username = 'hello@alwayssahi.com';             // SMTP username
    // $mail->Password = 'noPasswordSorry';                  // SMTP password
    // $mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
    // $mail->Port = 465;                                    // TCP port to connect to

    // Email Settings
    // $mail->setFrom('hello@alwayssahi.com', 'Support @Alwayssahi');
    // $mail->addAddress('alwayssahi@gmail.com', 'Team');                  // Add a recipient
    //$mail->addAddress('ellen@example.com');                // Name is optional
    //$mail->addReplyTo($email, $name);
    //$mail->addCC('cc@example.com');
    //$mail->addBCC('bcc@example.com');

    // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
    // $mail->isHTML(true);                                     // Set email format to HTML

    // $mail->Subject = 'Support Ticket Generated by ( ' . $id . ' )';
    // $mail->Body    = 'Hello Always Sahi Solutions Pvt Ltd, <br><br>This is <b>' . $name . ', ID: ' . $id . '</b>,<br>I have generated this support ticket for the reason mentioned below: <br><br>' . $description;
    // $mail->AltBody = 'Hello Always Sahi Solutions Pvt Ltd, This is ' . $name . ', ID: ' . $id . ',I have generated this support ticket for the reason mentioned below: ' . $description;

    // if (!$mail->send()) {
    //     echo 'Message could not be sent.';
    //     echo 'Mailer Error: ' . $mail->ErrorInfo;
    // } else {
    //     echo 'Message has been sent';
    // }

}
